apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: cert-manager
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-ssm
      kind: ClusterSecretStore
    target:
      name: cloudflare-api-token
    data:
      - secretKey: api-token
        remoteRef:
          key: /bagend/cloudflare/api_token
